### ISSUE TITLE
Bug: Projects details pop-up text is blurry on Chrome

### ISSUE THREAD

**Issue by Alex-Cannon** [JarethRader/portfolio#1]

**Comment by JarethRader** [comment]
This is due to the way [Chrome handles animations](https://bugs.chromium.org/p/chromium/issues/detail?id=521364). This might also be a problem in Safari, though I haven't checked.

The way around this might be to scale up the component when it is initially rendered, then scale it down so it is at a higher resolution and should fix the blur, or I can remove the translation in the animation and make the modal fade in and out.
